# Generated by Django 3.1.2 on 2020-10-20 22:34
import os
from django.db import migrations, models, connection


def load_data_from_sql(apps, schema_editor):
    file_path = os.path.join(os.path.dirname(__file__), 'bincom_test.sql')
    sql_statement = open(file_path).read()
    
    with connection.cursor() as c:
        c.execute(sql_statement)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_data_from_sql),
    ]
